env:
  global:
    - CC_TEST_REPORTER_ID=a3553b48911219005d977b9924fcdaee2bf3caeb1e822b77ea34ee8f8b39b97c
language: python
python:
  - 3.8

before_install:
  - pip install poetry

install:
  - make install

script:
  - make check
